/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int b_eq_function(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int b_eq_function_alloc_mem(void);
extern "C" int b_eq_function_init_mem(int mem);
extern "C" void b_eq_function_free_mem(int mem);
extern "C" int b_eq_function_checkout(void);
extern "C" void b_eq_function_release(int mem);
extern "C" void b_eq_function_incref(void);
extern "C" void b_eq_function_decref(void);
extern "C" casadi_int b_eq_function_n_in(void);
extern "C" casadi_int b_eq_function_n_out(void);
extern "C" casadi_real b_eq_function_default_in(casadi_int i);
extern "C" const char* b_eq_function_name_in(casadi_int i);
extern "C" const char* b_eq_function_name_out(casadi_int i);
extern "C" const casadi_int* b_eq_function_sparsity_in(casadi_int i);
extern "C" const casadi_int* b_eq_function_sparsity_out(casadi_int i);
extern "C" int b_eq_function_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int b_eq_function_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define b_eq_function_SZ_ARG 7
#define b_eq_function_SZ_RES 2
#define b_eq_function_SZ_IW 0
#define b_eq_function_SZ_W 690
extern "C" int A_eq_function(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int A_eq_function_alloc_mem(void);
extern "C" int A_eq_function_init_mem(int mem);
extern "C" void A_eq_function_free_mem(int mem);
extern "C" int A_eq_function_checkout(void);
extern "C" void A_eq_function_release(int mem);
extern "C" void A_eq_function_incref(void);
extern "C" void A_eq_function_decref(void);
extern "C" casadi_int A_eq_function_n_in(void);
extern "C" casadi_int A_eq_function_n_out(void);
extern "C" casadi_real A_eq_function_default_in(casadi_int i);
extern "C" const char* A_eq_function_name_in(casadi_int i);
extern "C" const char* A_eq_function_name_out(casadi_int i);
extern "C" const casadi_int* A_eq_function_sparsity_in(casadi_int i);
extern "C" const casadi_int* A_eq_function_sparsity_out(casadi_int i);
extern "C" int A_eq_function_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int A_eq_function_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define A_eq_function_SZ_ARG 7
#define A_eq_function_SZ_RES 2
#define A_eq_function_SZ_IW 43
#define A_eq_function_SZ_W 3301
